# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hand_pb2 as hand__pb2


class HandTrackingServiceStub(object):
    """The hand tracking service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamHandUpdates = channel.stream_stream(
                '/handtracking.HandTrackingService/StreamHandUpdates',
                request_serializer=hand__pb2.HandUpdate.SerializeToString,
                response_deserializer=hand__pb2.HandUpdateAck.FromString,
                )


class HandTrackingServiceServicer(object):
    """The hand tracking service definition.
    """

    def StreamHandUpdates(self, request_iterator, context):
        """Sends a stream of hand updates from the client (Swift) to the server (Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandTrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamHandUpdates': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamHandUpdates,
                    request_deserializer=hand__pb2.HandUpdate.FromString,
                    response_serializer=hand__pb2.HandUpdateAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'handtracking.HandTrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HandTrackingService(object):
    """The hand tracking service definition.
    """

    @staticmethod
    def StreamHandUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/handtracking.HandTrackingService/StreamHandUpdates',
            hand__pb2.HandUpdate.SerializeToString,
            hand__pb2.HandUpdateAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
