# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handtracking.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12handtracking.proto\x12\x0chandtracking\"\xca\x01\n\nHandUpdate\x12\x30\n\tleft_hand\x18\x01 \x01(\x0b\x32\x1d.handtracking.HandUpdate.Hand\x12\x31\n\nright_hand\x18\x02 \x01(\x0b\x32\x1d.handtracking.HandUpdate.Hand\x1aW\n\x04Hand\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\n\n\x02qx\x18\x04 \x01(\x02\x12\n\n\x02qy\x18\x05 \x01(\x02\x12\n\n\x02qz\x18\x06 \x01(\x02\x12\n\n\x02qw\x18\x07 \x01(\x02\" \n\rHandUpdateAck\x12\x0f\n\x07message\x18\x01 \x01(\t2b\n\x13HandTrackingService\x12K\n\x11StreamHandUpdates\x12\x18.handtracking.HandUpdate\x1a\x18.handtracking.HandUpdate\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'handtracking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HANDUPDATE']._serialized_start=37
  _globals['_HANDUPDATE']._serialized_end=239
  _globals['_HANDUPDATE_HAND']._serialized_start=152
  _globals['_HANDUPDATE_HAND']._serialized_end=239
  _globals['_HANDUPDATEACK']._serialized_start=241
  _globals['_HANDUPDATEACK']._serialized_end=273
  _globals['_HANDTRACKINGSERVICE']._serialized_start=275
  _globals['_HANDTRACKINGSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
