// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: handtracking.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - handtracking.HandTrackingService

/// Namespace containing generated types for the "handtracking.HandTrackingService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Handtracking_HandTrackingService {
    /// Service descriptor for the "handtracking.HandTrackingService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "handtracking.HandTrackingService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "StreamHandUpdates" metadata.
        public enum StreamHandUpdates {
            /// Request type for "StreamHandUpdates".
            public typealias Input = Handtracking_HandUpdate
            /// Response type for "StreamHandUpdates".
            public typealias Output = Handtracking_HandUpdate
            /// Descriptor for "StreamHandUpdates".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "handtracking.HandTrackingService"),
                method: "StreamHandUpdates"
            )
        }
        /// Descriptors for all methods in the "handtracking.HandTrackingService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            StreamHandUpdates.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "handtracking.HandTrackingService" service.
    public static let handtracking_HandTrackingService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "handtracking.HandTrackingService")
}

// MARK: handtracking.HandTrackingService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Handtracking_HandTrackingService {
    /// Streaming variant of the service protocol for the "handtracking.HandTrackingService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "StreamHandUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Handtracking_HandUpdate` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request.
        /// - Returns: A streaming response of `Handtracking_HandUpdate` messages.
        func streamHandUpdates(
            request: GRPCCore.StreamingServerRequest<Handtracking_HandUpdate>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Handtracking_HandUpdate>
    }

    /// Service protocol for the "handtracking.HandTrackingService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``.
    public protocol ServiceProtocol: Handtracking_HandTrackingService.StreamingServiceProtocol {
        /// Handle the "StreamHandUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Handtracking_HandUpdate` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request.
        /// - Returns: A streaming response of `Handtracking_HandUpdate` messages.
        func streamHandUpdates(
            request: GRPCCore.ServerRequest<Handtracking_HandUpdate>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Handtracking_HandUpdate>
    }

    /// Simple service protocol for the "handtracking.HandTrackingService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata.
    public protocol SimpleServiceProtocol: Handtracking_HandTrackingService.ServiceProtocol {
        /// Handle the "StreamHandUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A `Handtracking_HandUpdate` message.
        ///   - response: A response stream of `Handtracking_HandUpdate` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request.
        func streamHandUpdates(
            request: Handtracking_HandUpdate,
            response: GRPCCore.RPCWriter<Handtracking_HandUpdate>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Handtracking_HandTrackingService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Handtracking_HandTrackingService.Method.StreamHandUpdates.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Handtracking_HandUpdate>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Handtracking_HandUpdate>(),
            handler: { request, context in
                try await self.streamHandUpdates(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Handtracking_HandTrackingService.ServiceProtocol {
    public func streamHandUpdates(
        request: GRPCCore.StreamingServerRequest<Handtracking_HandUpdate>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Handtracking_HandUpdate> {
        let response = try await self.streamHandUpdates(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Handtracking_HandTrackingService.SimpleServiceProtocol {
    public func streamHandUpdates(
        request: GRPCCore.ServerRequest<Handtracking_HandUpdate>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Handtracking_HandUpdate> {
        return GRPCCore.StreamingServerResponse<Handtracking_HandUpdate>(
            metadata: [:],
            producer: { writer in
                try await self.streamHandUpdates(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}
